#  Author: Austin Raney
#  Date:   2018-11-29
#  Last Modified by:   Austin Raney
#  Last Modified time: 2018-11-29

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Append netCDF 4.6.1 and 4.4.4 to path and set path
use netcdf461Intel
export NETCDF=/share/apps/netcdf.new/intel/

# Append openMPI to path 
use openmpiIntel

# Set WRF HYDRO Specific Vars
export WRF_HYDRO=1
export HYDRO_D=1

# Aliases that might be useful for mpi and ifort related things
alias impirun='/share/apps/openmpi/Intel/1.6.4/bin/mpirun'
alias iman='man -M/share/apps/netcdf.new/intel/share/man'
# Bonus: Check your wrf hydro environment - up you to maintain to your needs.
alias wrfenv='printenv | egrep -i "(HYDRO|NUDG|PRECIP|CHAN_CONN|^NETCDF|^LDFLAGS|^ifort)" | egrep -v PWD'